# Generated by Django 2.0.4 on 2018-04-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lenght_of_arms',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина рук'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenght_of_head',
            field=models.FloatField(blank=True, null=True, verbose_name='Обхват головы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenght_of_legs',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина ног'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenght_of_trunk',
            field=models.FloatField(blank=True, null=True, verbose_name='Обхавт туловища'),
        ),
    ]
