# Generated by Django 2.0.4 on 2018-05-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_auth', '0003_auto_20180509_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lenght_of_arms',
            new_name='length_of_arms',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lenght_of_head',
            new_name='length_of_head',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lenght_of_legs',
            new_name='length_of_legs',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lenght_of_trunk',
            new_name='length_of_waist_girth',
        ),
    ]
