# Generated by Django 2.0.4 on 2018-05-05 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10, verbose_name='RGB значение')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField(verbose_name='Стоимость единицы материала')),
                ('footage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=32)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_completion', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cutter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('order_item_active', models.BooleanField(default=False)),
                ('sewing_cost', models.FloatField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_for_orderItem', to='shop.Catalog')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_for_orderItem', to='shop.Color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_for_orderItem', to='shop.Material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sewing_time', models.TimeField()),
                ('k_lenght_of_arms', models.FloatField(default=0.0)),
                ('k_lenght_of_legs', models.FloatField(default=0.0)),
                ('k_lenght_of_trunk', models.FloatField(default=0.0)),
                ('k_lenght_of_head', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='color',
            field=models.ManyToManyField(related_name='catalog_for_color', to='shop.Color'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='material',
            field=models.ManyToManyField(related_name='catalog_for_material', to='shop.Material'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Type'),
        ),
    ]
