# Generated by Django 2.0.4 on 2018-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180509_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_completion',
            field=models.DateTimeField(blank=True),
        ),
    ]
