# Generated by Django 2.0.4 on 2018-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'не оплачено'), ('work', 'в работе'), ('ready', 'готово')], default='unpaid', max_length=10),
        ),
    ]
