# Generated by Django 2.0.4 on 2018-05-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180509_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='material',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='k_lenght_of_arms',
            new_name='k_length_of_arms',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='k_lenght_of_head',
            new_name='k_length_of_head',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='k_lenght_of_legs',
            new_name='k_length_of_legs',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='k_lenght_of_trunk',
            new_name='k_length_of_waist_girth',
        ),
    ]
