# Generated by Django 2.0.4 on 2018-05-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180512_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='catalog',
            new_name='model_from_catalog',
        ),
    ]
